/*
  Auto-generated by Spline
*/
import React from 'react';
import {useNavigate} from 'react-router-dom';
import useSpline from '@splinetool/r3f-spline';
import {OrthographicCamera} from '@react-three/drei';
import {
  globe,
  vr,
  messageList,
  messageCreate,
  settings,
} from '../../apis/router.ts';

export default function Scene({...props}) {
  const {nodes, materials} = useSpline(
    'https://prod.spline.design/tmr-ErPtMDTMnx0L/scene.splinecode',
  );

  const navigate = useNavigate();
  const moveGlobe = () => navigate(globe());
  const moveVR = () => navigate(vr());
  const moveMessage = () => navigate(messageList());
  const moveCreate = () => navigate(messageCreate());
  const moveSettings = () => navigate(settings());

  return (
    <>
      <color attach="background" args={['#d9d7f3']} />
      <group {...props} dispose={null}>
        <group
          name="book"
          position={[334, 211.28, -3.13]}
          rotation={[0.09, 0.36, -0.26]}
          scale={0.34}
          onClick={() => moveMessage()}>
          <mesh
            name="paper"
            geometry={nodes.paper.geometry}
            material={materials.paper}
            castShadow
            receiveShadow
            position={[39.79, 38.2, -9.98]}
            rotation={[0, 0, -Math.PI]}
            scale={[2.81, 2.91, 1.67]}
          />
          <mesh
            name="coverback"
            geometry={nodes.coverback.geometry}
            material={materials.Cover}
            castShadow
            receiveShadow
            position={[2.4, 0, -36.42]}
            rotation={[0, 0, -Math.PI]}
            scale={[2.76, 2.91, 2.79]}
          />
          <mesh
            name="darkpart"
            geometry={nodes.darkpart.geometry}
            material={materials.Cover}
            castShadow
            receiveShadow
            position={[-141.29, 0, -1.26]}
            rotation={[-Math.PI, -Math.PI / 2, 0]}
            scale={[3.66, 2.91, 5.27]}
          />
          <mesh
            name="coverfront"
            geometry={nodes.coverfront.geometry}
            material={materials.Cover}
            castShadow
            receiveShadow
            position={[1.72, 0, 36.01]}
            rotation={[0, 0, -Math.PI]}
            scale={[2.76, 2.91, 3.2]}
          />
        </group>
        <group
          name="object_saturno"
          position={[-398.58, 267, 80]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.38}>
          <mesh
            name="ring2"
            geometry={nodes.ring2.geometry}
            material={materials.rings}
            castShadow
            receiveShadow
            position={[0, 1.89, 0]}
            rotation={[1.88, -0.37, 3.1]}
            scale={[4.89, 4.89, 0.79]}
          />
          <mesh
            name="ring1"
            geometry={nodes.ring1.geometry}
            material={materials.rings}
            castShadow
            receiveShadow
            position={[0, 1.89, 0]}
            rotation={[1.88, -0.37, 3.1]}
            scale={[3.77, 3.77, 0.61]}
          />
          <mesh
            name="saturno"
            geometry={nodes.saturno.geometry}
            material={materials.planet}
            castShadow
            receiveShadow
            position={[2.5, 0, -3.31]}
            rotation={[0.22, 0.04, -0.37]}
            scale={2.26}
            onClick={() => moveGlobe()}
          />
        </group>
        <group name="bell" position={[241.34, 464, -8.09]} scale={0.19}>
          <mesh
            name="handle"
            geometry={nodes.handle.geometry}
            material={materials.pendul}
            castShadow
            receiveShadow
            position={[31.38, 149.49, -35.35]}
            rotation={[-0.23, 0, -2.37]}
            scale={0.92}
          />
          <mesh
            name="bell1"
            geometry={nodes.bell1.geometry}
            material={materials.bell}
            castShadow
            receiveShadow
            position={[3.27, 16.87, -3.88]}
            rotation={[-0.23, 0, -0.19]}
            scale={2.62}
            onClick={() => moveSettings()}
          />
          <mesh
            name="pendul"
            geometry={nodes.pendul.geometry}
            material={materials.pendul}
            castShadow
            receiveShadow
            position={[-25.43, -108.32, 24.93]}
            rotation={[-0.23, 0, -0.19]}
            scale={0.92}
          />
        </group>
        <group
          name="star"
          position={[-529.76, 318.7, 83.48]}
          rotation={[0, 0.32, 0]}
          scale={0.11}>
          <mesh
            name="star1"
            geometry={nodes.star1.geometry}
            material={materials.yellow}
            castShadow
            receiveShadow
            position={[-6.89, -18.18, 0]}
            scale={3.72}
          />
        </group>
        <group name="object_balloon" position={[-93.18, 375, -44]}>
          <mesh
            name="cord"
            geometry={nodes.cord.geometry}
            material={materials.Untitled}
            castShadow
            receiveShadow
            position={[-0.09, -106.61, 2.08]}
            rotation={[0, 0, -0.04]}
            scale={[0.04, 2.76, 0.04]}
          />
          <mesh
            name="baseballoon"
            geometry={nodes.baseballoon.geometry}
            material={materials.ballon}
            castShadow
            receiveShadow
            position={[4.15, -20.25, 2.36]}
            scale={0.31}
          />
          <mesh
            name="balloon"
            geometry={nodes.balloon.geometry}
            material={materials.ballon}
            castShadow
            receiveShadow
            position={[-17.4, 114.61, -6.75]}
            rotation={[0, 0, 0.14]}
            scale={1.28}
            onClick={() => moveCreate()}
          />
        </group>
        <mesh
          name="Floor"
          geometry={nodes.Floor.geometry}
          material={materials['Floor Material']}
          castShadow
          receiveShadow
          position={[122.58, -329.82, -359.33]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1}
        />
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.9}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-3389.844}
          shadow-camera-right={3389.844}
          shadow-camera-top={3389.844}
          shadow-camera-bottom={-3389.844}
          color="#fee5dd"
          position={[-533.7, 668.43, 796.96]}
        />
        <group name="Objects" position={[175.03, 5.04, -190.02]}>
          <group
            name="Chair"
            position={[-78.38, -181.1, 122.81]}
            rotation={[0, -Math.PI / 6, 0]}
            scale={1}>
            <mesh
              name="Cube 3"
              geometry={nodes['Cube 3'].geometry}
              material={materials.Stool}
              castShadow
              receiveShadow
              position={[-42.8, -31.85, -48.45]}
              rotation={[0.17, -0.03, -0.17]}
              scale={1}
            />
            <mesh
              name="Cube 31"
              geometry={nodes['Cube 31'].geometry}
              material={materials.Stool}
              castShadow
              receiveShadow
              position={[41.57, -32.53, -48.75]}
              rotation={[0.19, -0.09, 0.17]}
              scale={1}
            />
            <mesh
              name="Cube 2"
              geometry={nodes['Cube 2'].geometry}
              material={materials.Stool}
              castShadow
              receiveShadow
              position={[-43.1, -34.67, 48.83]}
              rotation={[-0.18, -0.03, -0.17]}
              scale={1}
            />
            <mesh
              name="Cube"
              geometry={nodes.Cube.geometry}
              material={materials.Stool}
              castShadow
              receiveShadow
              position={[41.74, -34.51, 48.55]}
              rotation={[-0.16, -0.09, 0.17]}
              scale={1}
            />
            <mesh
              name="Cylinder 3"
              geometry={nodes['Cylinder 3'].geometry}
              material={materials.Stool}
              castShadow
              receiveShadow
              position={[-0.14, -68.35, 0.22]}
              scale={0.85}
            />
            <mesh
              name="Cylinder 2"
              geometry={nodes['Cylinder 2'].geometry}
              material={materials['Cylinder 2 Material']}
              castShadow
              receiveShadow
              position={[-1.79, 84.88, 0.22]}
              scale={0.85}
            />
            <mesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={materials.Stool}
              castShadow
              receiveShadow
              position={[-1.79, 93.36, 0.22]}
              scale={0.85}
            />
          </group>
          <group name="table" position={[-442.78, -245.69, 115.3]}>
            <group
              name="book1"
              position={[-46.78, 127.46, -60.44]}
              rotation={[0, 0, 0]}
              scale={1}>
              <mesh
                name="Cube 32"
                geometry={nodes['Cube 32'].geometry}
                material={materials['Cube 32 Material']}
                castShadow
                receiveShadow
                position={[-0.15, 0.04, 0.61]}
                rotation={[-0.04, 0.49, 1.61]}
                scale={[0.38, 0.77, 0.58]}
              />
              <mesh
                name="Cube 33"
                geometry={nodes['Cube 33'].geometry}
                material={materials['Cube 33 Material']}
                castShadow
                receiveShadow
                position={[2.8, -6.42, 5.6]}
                rotation={[-0.04, 0.49, 1.61]}
                scale={[0.38, 0.77, 0.58]}
              />
            </group>
            <group
              name="book2"
              position={[-41.19, 105.95, -64.04]}
              rotation={[0, 0, 0]}
              scale={1}>
              <mesh
                name="Cube 21"
                geometry={nodes['Cube 21'].geometry}
                material={materials['Cube 21 Material']}
                castShadow
                receiveShadow
                position={[0.14, 0.01, 1]}
                rotation={[0, 0.74, Math.PI / 2]}
                scale={[0.59, 0.95, 0.8]}
              />
              <mesh
                name="Cube1"
                geometry={nodes.Cube1.geometry}
                material={materials['Cube1 Material']}
                castShadow
                receiveShadow
                position={[5.38, -9.87, 5.9]}
                rotation={[0, 0.74, Math.PI / 2]}
                scale={[0.59, 0.95, 0.8]}
              />
            </group>
            <group name="book 3" position={[-12.71, 101.21, 32.16]}>
              <mesh
                name="Cube 4"
                geometry={nodes['Cube 4'].geometry}
                material={materials['Cube 4 Material']}
                castShadow
                receiveShadow
                position={[0.22, 0.21, 0.74]}
                rotation={[-0.01, 1.29, 1.56]}
                scale={[0.39, 0.7, 0.58]}
              />
              <mesh
                name="Cube 41"
                geometry={nodes['Cube 41'].geometry}
                material={materials['Cube 41 Material']}
                castShadow
                receiveShadow
                position={[5.63, -6.5, 1.6]}
                rotation={[-0.01, 1.29, 1.56]}
                scale={[0.39, 0.7, 0.58]}
              />
            </group>
            <group
              name="coffee"
              position={[64.43, 135.05, -32.14]}
              scale={0.48}>
              <mesh
                name="coffeeStraw"
                geometry={nodes.coffeeStraw.geometry}
                material={materials['coffeeStraw Material']}
                castShadow
                receiveShadow
                position={[-14.56, 41.51, 5.45]}
                rotation={[0.26, 0.02, 0.08]}
                scale={1}
              />
              <mesh
                name="coffeeLid"
                geometry={nodes.coffeeLid.geometry}
                material={materials['coffeeLid Material']}
                castShadow
                receiveShadow
                position={[0, 18.91, 0]}
                scale={1}
              />
              <mesh
                name="coffeeRing"
                geometry={nodes.coffeeRing.geometry}
                material={materials['coffeeRing Material']}
                castShadow
                receiveShadow
                position={[-0.39, -30.22, -1.03]}
                scale={1}
              />
              <mesh
                name="coffeeBody"
                geometry={nodes.coffeeBody.geometry}
                material={materials['coffeeBody Material']}
                castShadow
                receiveShadow
                position={[-0.39, -37.79, -1.03]}
                scale={1}
              />
            </group>
            <mesh
              name="Cube 42"
              geometry={nodes['Cube 42'].geometry}
              material={materials['Cube 42 Material']}
              castShadow
              receiveShadow
              position={[-0.36, -8.7, 88.76]}
              rotation={[-0.17, -Math.PI / 2, 0]}
              scale={1}
            />
            <mesh
              name="Cube 34"
              geometry={nodes['Cube 34'].geometry}
              material={materials['Cube 34 Material']}
              castShadow
              receiveShadow
              position={[85.14, -8.7, 3.26]}
              rotation={[0, 0, 0.17]}
              scale={1}
            />
            <mesh
              name="Cube 43"
              geometry={nodes['Cube 43'].geometry}
              material={materials['Cube 43 Material']}
              castShadow
              receiveShadow
              position={[-0.36, -5.16, -82.24]}
              rotation={[0.17, -Math.PI / 2, 0]}
              scale={1}
            />
            <mesh
              name="Cube 22"
              geometry={nodes['Cube 22'].geometry}
              material={materials['Cube 22 Material']}
              castShadow
              receiveShadow
              position={[-85.86, -5.16, 3.26]}
              rotation={[0, 0, -0.17]}
              scale={1}
            />
            <mesh
              name="Cylinder1"
              geometry={nodes.Cylinder1.geometry}
              material={materials['Cylinder1 Material']}
              castShadow
              receiveShadow
              position={[0, 81.85, 0]}
            />
          </group>
          <mesh
            name="groundCube"
            geometry={nodes.groundCube.geometry}
            material={materials['Ground shapes']}
            castShadow
            receiveShadow
            position={[407.8, -280.54, -223.32]}
            rotation={[-Math.PI / 2, 0, 0.26]}
            scale={1}
          />
          <mesh
            name="groundPyramid"
            geometry={nodes.groundPyramid.geometry}
            material={materials['groundPyramid Material']}
            castShadow
            receiveShadow
            position={[-394.91, -275.6, 211.76]}
            rotation={[-0.06, -0.14, 0.91]}
            scale={1}
          />
          <mesh
            name="groundSphere"
            geometry={nodes.groundSphere.geometry}
            material={materials['Ground shapes']}
            castShadow
            receiveShadow
            position={[54.31, -290.76, -214.49]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <group name="lamp" position={[404.45, 18.8, -9.09]}>
            <mesh
              name="Sphere 2"
              geometry={nodes['Sphere 2'].geometry}
              material={materials['Sphere 2 Material']}
              castShadow
              receiveShadow
              position={[-62.28, 256.7, 49.13]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 7"
              geometry={nodes['Cube 7'].geometry}
              material={materials['Cube 7 Material']}
              castShadow
              receiveShadow
              position={[-51.78, 282.28, 41.49]}
              rotation={[0, 0.7, Math.PI / 3]}
              scale={1}
            />
            <mesh
              name="Cube 6"
              geometry={nodes['Cube 6'].geometry}
              material={materials['Cube 6 Material']}
              castShadow
              receiveShadow
              position={[47.95, -248.79, -37.78]}
              rotation={[0, 0.7, 0]}
            />
            <mesh
              name="Cylinder 21"
              geometry={nodes['Cylinder 21'].geometry}
              material={materials['Plastic blue']}
              castShadow
              receiveShadow
              position={[49.13, -333.68, -36.39]}
              rotation={[0, 0.7, 0]}
            />
          </group>
          <group
            name="Group 7"
            position={[295.22, -178.47, 51.59]}
            scale={0.85}>
            <mesh
              name="Cube 12"
              geometry={nodes['Cube 12'].geometry}
              material={materials['Cube 12 Material']}
              castShadow
              receiveShadow
              position={[2.69, -4.14, 10.5]}
              rotation={[2.94, 1.13, -2.96]}
              scale={1}
            />
            <mesh
              name="Cylinder 22"
              geometry={nodes['Cylinder 22'].geometry}
              material={materials['Cylinder 22 Material']}
              castShadow
              receiveShadow
              position={[-6.01, -88.9, 16.97]}
            />
            <mesh
              name="Cube 9"
              geometry={nodes['Cube 9'].geometry}
              material={materials['Plastic green']}
              castShadow
              receiveShadow
              position={[-9.73, 111.05, 11.87]}
              rotation={[0, 0.99, 0]}
              scale={1}
            />
            <mesh
              name="Cube 8"
              geometry={nodes['Cube 8'].geometry}
              material={materials['Cube 8 Material']}
              castShadow
              receiveShadow
              position={[19.63, 80.03, 5.85]}
              rotation={[-0.33, -1.3, -0.3]}
              scale={1}
            />
            <mesh
              name="Cube 10"
              geometry={nodes['Cube 10'].geometry}
              material={materials['Cube 10 Material']}
              castShadow
              receiveShadow
              position={[12.32, 119.61, 29.02]}
              rotation={[-3.01, -0.73, -3.03]}
              scale={1}
            />
            <mesh
              name="Cube 11"
              geometry={nodes['Cube 11'].geometry}
              material={materials['Cube 11 Material']}
              castShadow
              receiveShadow
              position={[-27.62, -3.9, 28.51]}
              rotation={[-2.72, 1.12, 2.73]}
              scale={1}
            />
            <mesh
              name="Cube 71"
              geometry={nodes['Cube 71'].geometry}
              material={materials['Cube 71 Material']}
              castShadow
              receiveShadow
              position={[2.77, 52.94, -5.43]}
              rotation={[0, 0.26, 0]}
              scale={1}
            />
            <mesh
              name="Cube 61"
              geometry={nodes['Cube 61'].geometry}
              material={materials['Cube 61 Material']}
              castShadow
              receiveShadow
              position={[-5.26, -137.14, 16.39]}
            />
          </group>
        </group>
        <group
          name="Character"
          position={[65.57, -56.59, 12.79]}
          rotation={[0, -Math.PI / 6, 0]}
          scale={1}>
          <group
            name="head"
            position={[0.3, 274.13, -46.65]}
            rotation={[0.12, -0.01, -0.09]}
            scale={1}>
            <mesh
              name="Cube 15"
              geometry={nodes['Cube 15'].geometry}
              material={materials['Cube 15 Material']}
              castShadow
              receiveShadow
              position={[11.41, -1.05, 29.62]}
              rotation={[0, Math.PI / 9, 0]}
              scale={1}
            />
            <mesh
              name="Cube 14"
              geometry={nodes['Cube 14'].geometry}
              material={materials['Cube 14 Material']}
              castShadow
              receiveShadow
              position={[-21.35, -1.05, 28.72]}
              rotation={[0, -Math.PI / 9, 0]}
              scale={1}
            />
            <mesh
              name="Cube 13"
              geometry={nodes['Cube 13'].geometry}
              material={materials.Eyebrows}
              castShadow
              receiveShadow
              position={[-21.98, 8.29, 29.17]}
              rotation={[-0.04, -0.41, -0.2]}
              scale={1}
            />
            <mesh
              name="Cube 121"
              geometry={nodes['Cube 121'].geometry}
              material={materials.Eyebrows}
              castShadow
              receiveShadow
              position={[12.6, 4.37, 31.35]}
              rotation={[-0.1, 0.28, 0.2]}
              scale={1}
            />
            <mesh
              name="Ellipse 2"
              geometry={nodes['Ellipse 2'].geometry}
              material={materials['Ellipse 2 Material']}
              castShadow
              receiveShadow
              position={[-24.64, -21.51, 23.43]}
              rotation={[0.26, -0.58, 0]}
              scale={1}
            />
            <mesh
              name="Ellipse"
              geometry={nodes.Ellipse.geometry}
              material={materials['Ellipse Material']}
              castShadow
              receiveShadow
              position={[16.55, -20.69, 24.79]}
              rotation={[0.26, 0.56, 0]}
              scale={1}
            />
            <mesh
              name="Cube 91"
              geometry={nodes['Cube 91'].geometry}
              material={materials['Cube 91 Material']}
              castShadow
              receiveShadow
              position={[1.3, -27.6, 26.37]}
              rotation={[0.14, -0.46, -2.93]}
              scale={[0.93, 1, 0.67]}
            />
            <mesh
              name="Cube 23"
              geometry={nodes['Cube 23'].geometry}
              material={materials['Cube 23 Material']}
              castShadow
              receiveShadow
              position={[38.89, -9, -6.07]}
              scale={[-1, 1, 1]}
            />
            <mesh
              name="Cube2"
              geometry={nodes.Cube2.geometry}
              material={materials['Cube2 Material']}
              castShadow
              receiveShadow
              position={[-46.02, -12.67, -6.07]}
            />
            <mesh
              name="hair"
              geometry={nodes.hair.geometry}
              material={materials['hair Material']}
              castShadow
              receiveShadow
              position={[-3.26, 39.95, -32.33]}
              rotation={[-Math.PI / 6, 0, 0]}
              scale={[1.04, 1, 1]}
            />
            <mesh
              name="Sphere 21"
              geometry={nodes['Sphere 21'].geometry}
              material={materials['Sphere 21 Material']}
              castShadow
              receiveShadow
              position={[-2.88, -8.51, -8.67]}
            />
          </group>
          <group
            name="Glasses"
            position={[-1.71, 274.53, -50.15]}
            rotation={[0.22, -0.02, -0.05]}
            scale={1.22}>
            <mesh
              name="Cylinder2"
              geometry={nodes.Cylinder2.geometry}
              material={materials['Cylinder2 Material']}
              castShadow
              receiveShadow
              position={[0.06, 5.4, 33.96]}
              rotation={[0, 0, Math.PI / 2]}
              scale={1}
            />
            <mesh
              name="Cube 35"
              geometry={nodes['Cube 35'].geometry}
              material={materials['Cube 35 Material']}
              castShadow
              receiveShadow
              position={[33.6, 1.21, 30.85]}
              rotation={[0, 1.4, 0]}
              scale={1}
            />
            <mesh
              name="Cube 24"
              geometry={nodes['Cube 24'].geometry}
              material={materials['Cube 24 Material']}
              castShadow
              receiveShadow
              position={[-33, 0.81, 30.81]}
              rotation={[-Math.PI, 1.4, -Math.PI]}
              scale={1}
            />
            <mesh
              name="Torus 2"
              geometry={nodes['Torus 2'].geometry}
              material={materials['Torus 2 Material']}
              castShadow
              receiveShadow
              position={[18.4, 0.83, 33.98]}
              rotation={[0, 0, -0.02]}
              scale={1}
            />
            <mesh
              name="Torus"
              geometry={nodes.Torus.geometry}
              material={materials['Torus Material']}
              castShadow
              receiveShadow
              position={[-17.94, 1.59, 33.98]}
              rotation={[0, 0, -0.02]}
              scale={1}
            />
          </group>
          <group
            name="computer"
            position={[20.2, 130.01, 34.64]}
            rotation={[-2.95, -0.21, -3.09]}
            scale={[0.56, 0.61, 0.61]}>
            <mesh
              name="computerScreen"
              geometry={nodes.computerScreen.geometry}
              material={materials['computerScreen Material']}
              castShadow
              receiveShadow
              position={[0, 4.2, -71.3]}
              rotation={[-0.17, 0, 0]}
              scale={1}
            />
            <mesh
              name="computerTrackpad"
              geometry={nodes.computerTrackpad.geometry}
              material={materials['computerTrackpad Material']}
              castShadow
              receiveShadow
              position={[0, -66.01, 62.64]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.83}
            />
            <mesh
              name="computerKeyboard"
              geometry={nodes.computerKeyboard.geometry}
              material={materials['computerKeyboard Material']}
              castShadow
              receiveShadow
              position={[0, -62.82, -3.88]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.83}
            />
            <mesh
              name="computerBodyBottom"
              geometry={nodes.computerBodyBottom.geometry}
              material={materials['computerBodyBottom Material']}
              castShadow
              receiveShadow
              position={[0, -66.85, 15.84]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="computerBodyTop"
              geometry={nodes.computerBodyTop.geometry}
              material={materials['computerBodyTop Material']}
              castShadow
              receiveShadow
              position={[0, -0.24, -76.29]}
              rotation={[-0.17, 0, 0]}
              scale={1}
            />
          </group>
          <group
            name="Group 5"
            position={[-29.31, -168.52, 15.44]}
            rotation={[0.87, 0, 0.26]}
            scale={[1.8, 1.76, 1.71]}>
            <mesh
              name="Torus 21"
              geometry={nodes['Torus 21'].geometry}
              material={materials['Torus 21 Material']}
              castShadow
              receiveShadow
              position={[0.03, -7.05, 7.24]}
              rotation={[0, 0, -0.61]}
              scale={1}
            />
            <mesh
              name="Torus1"
              geometry={nodes.Torus1.geometry}
              material={materials['Torus1 Material']}
              castShadow
              receiveShadow
              position={[0, -5.6, 2.14]}
              rotation={[0, 0, -Math.PI / 4]}
              scale={1}
            />
            <mesh
              name="Cube 44"
              geometry={nodes['Cube 44'].geometry}
              material={materials['Cube 44 Material']}
              castShadow
              receiveShadow
              position={[0.03, -5.56, -27.01]}
              rotation={[Math.PI, 0, 0]}
              scale={0.9}
            />
            <mesh
              name="Cube 36"
              geometry={nodes['Cube 36'].geometry}
              material={materials['Sneakers white']}
              castShadow
              receiveShadow
              position={[-0.5, -10.06, 16.62]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 25"
              geometry={nodes['Cube 25'].geometry}
              material={materials['Sneakers blue']}
              castShadow
              receiveShadow
              position={[-0.4, -9.73, 0.39]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Rectangle 2"
              geometry={nodes['Rectangle 2'].geometry}
              material={materials['Sneakers white']}
              castShadow
              receiveShadow
              position={[-0.45, -20.06, -0.01]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
          <group
            name="Group 4"
            position={[28.78, -238.18, 130.7]}
            rotation={[-0.09, 0, 0]}
            scale={[1.8, 1.66, 1.8]}>
            <mesh
              name="Torus 22"
              geometry={nodes['Torus 22'].geometry}
              material={materials['Torus 22 Material']}
              castShadow
              receiveShadow
              position={[0.03, -7.05, 7.24]}
              rotation={[0, 0, -0.61]}
              scale={1}
            />
            <mesh
              name="Torus2"
              geometry={nodes.Torus2.geometry}
              material={materials['Torus2 Material']}
              castShadow
              receiveShadow
              position={[0, -5.6, 2.14]}
              rotation={[0, 0, -Math.PI / 4]}
              scale={1}
            />
            <mesh
              name="Cube 45"
              geometry={nodes['Cube 45'].geometry}
              material={materials['Cube 45 Material']}
              castShadow
              receiveShadow
              position={[0.03, -5.56, -27.01]}
              rotation={[Math.PI, 0, 0]}
              scale={0.9}
            />
            <mesh
              name="Cube 37"
              geometry={nodes['Cube 37'].geometry}
              material={materials['Sneakers white']}
              castShadow
              receiveShadow
              position={[-0.5, -10.06, 16.62]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 26"
              geometry={nodes['Cube 26'].geometry}
              material={materials['Sneakers blue']}
              castShadow
              receiveShadow
              position={[-0.4, -9.73, 0.39]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Rectangle 21"
              geometry={nodes['Rectangle 21'].geometry}
              material={materials['Sneakers white']}
              castShadow
              receiveShadow
              position={[-0.45, -20.06, -0.01]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
          </group>
          <mesh
            name="Cube 111"
            geometry={nodes['Cube 111'].geometry}
            material={materials['Cube 111 Material']}
            castShadow
            receiveShadow
            position={[24.35, 169.23, -43.04]}
            rotation={[-0.72, 0.22, 0.03]}
            scale={[1.48, 0.51, 0.46]}
          />
          <mesh
            name="pen"
            geometry={nodes.pen.geometry}
            material={materials['Plastic blue']}
            castShadow
            receiveShadow
            position={[-51.59, 235.05, -45.23]}
            rotation={[0.48, -0.23, -0.21]}
            scale={1}
          />
          <mesh
            name="裤子"
            geometry={nodes.裤子.geometry}
            material={materials['裤子 Material']}
            castShadow
            receiveShadow
            position={[-3.67, 20.63, -73.2]}
          />
          <mesh
            name="Cube 17"
            geometry={nodes['Cube 17'].geometry}
            material={materials['Cube 17 Material']}
            castShadow
            receiveShadow
            position={[-2.19, 116.88, -71.94]}
            scale={[1, 1, 0.95]}
          />
          <mesh
            name="body"
            geometry={nodes.body.geometry}
            material={materials['body Material']}
            castShadow
            receiveShadow
            position={[-5.07, 112.17, -71.74]}
          />
        </group>
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={0.54}
          far={100000}
          near={-100000}
          position={[-25.13, 296.98, 997.83]}
          rotation={[-0.31, -0.1, -0.03]}
        />
        <hemisphereLight
          name="Default Ambient Light"
          intensity={0.75}
          color="#eaeaea"
        />
      </group>
    </>
  );
}
